### ISSUE TITLE
Problems with par and non integers? i.e. Long/Double/BigDecimal ?

### ISSUE THREAD

**Issue by fancellu** [scala-blitz/scala-blitz#46]
Using 2.11.1 and 1.1 

val ran=(0L until 15000L)

ran.toPar.reduce(_ + _)

Compiler says

Description Resource    Path    Location    Type
value reduce is not a member of scala.collection.par.Par[scala.collection.immutable.NumericRange.Exclusive[Long]]   ScalaBlitzTest.scala    /scala/src  line 43 Scala Problem

Similar if Double, or BigDecimal

If range gets too big then will not do reduce properly because of overflow, hence need to move away from Integer.

Is this a known issue?

**Comment by DarkDimius** [comment]
`NumericRange`s are not supported currently, only `scala.collection.immutable.Range` and its subclasses are.

**Comment by DarkDimius** [comment]
Reason for not supporting is that I agree that they should be deprecated,
please see this link for reason https://groups.google.com/d/msg/scala-internals/JleZ0hu-bLs/_LCo2L7kva8J

**Comment by fancellu** [comment]
That seems fair enough.

What about Lists?

e.g.

val li=(0L until 15000000L).toList
        li.toPar.reduce(_ + _)

value reduce is not a member of scala.collection.par.Par[List[Long]]

Does similar if I map(_.toDouble)

Dino.

**Comment by DarkDimius** [comment]
toPar conversion is always available. But the operation provider is required separately.
While ScalaBlitz defines parallel operation providers for Ranges, there are no parallel operations defined for lists, as lists cannot be efficiently iterated in parallel.
This is intentional, as while Scala Parallel collections allow writing `list.par` this implicitly copies data to `ParVector`.
For more verbose description please have a look on talk on Scala Exchange'13 https://skillsmatter.com/skillscasts/4467-macro-based-scala-parallel-collections
