### ISSUE TITLE
Is it possible to create parallel Streams?

### ISSUE THREAD

**Issue by nightscape** [scala-blitz/scala-blitz#47]
Hi!

I am searching for a possibility to do parallel computations on Streams in order to meet memory restrictions on huge data sets.
Currently, [Skiis](https://github.com/aboisvert/skiis) seems to be the only library that provides such functionality, but it would be very nice if this were included in a more extensive library like scala-blitz.

What would be a good starting point to create such functionality?

Best
  Martin

**Comment by DarkDimius** [comment]
Hi Martin,
There is a small problem with names in Scala Community now, as Scala has it's own `Stream`s that are not what Java calls `Stream`s. Java `Stream`s are more similar to Scala `Views`.

##### _In case you meant Scala Streams:_

ScalaBlitz was made as an effort to make parallel operations with as less overhead as possible. One of the requirements for doing so is using as little as possible interactions between threads, In order to achieve this in ScalaBlitz approach called "Work-Stealing Tree Scheduling" is used https://axel22.github.io/resources/docs/lcpc2013_submission_6.pdf that allows threads to reserve batches of work that they are going to process and rebalance this work between threads in runtime while maintaining low number of interactions.

On Streams you have a restriction that this collection is inherently sequential: linearized by the order of forcing element during traversal. This leads to requiring frequent interactions between threads in order to plan which element will be consumed by which thread. This effect can be seen in `Skiis` library that you refer eve. Take a look on the example in their README `(1 to 100000).par map (_ * 2) filter (_ % 2 == 0) reduce (_ + _)`: it's almost on par with Scala Parallel Collections which are known to introduce high per-element overhead. Similar code compiled by ScalaBlitz executes `3-4x` faster due to simply having less per-element overhead.

To sum up, while Streams can be an interesting destination to develop, it's not straightforward and requires careful research. If someone wants to work on this `ScalaBlitz` indeed could be a good ground to start with. If interested, we can have meeting to discuss ideas.

---

##### _In case you meant Scala Views:_

That indeed next direction of research that we will explore. 

The main difference between Views and Streams is that views are already based on an existing collection and scheduling on this collection can be used to plan parallel execution. And even more, this is already available in ScalaBlitz and can be reused. The remaining crucial part for making low-overhead views is making compile-time fusion possible.

There are multiple approaches for doing fusion, most coming from Haskel world, and there are several open questions in this topic, eg: while there are several proposed systems that can fuse both `zip`s and `flatMap`s most of them are complex and are new & not that tested in real-world applications. Then fusion system should be chosen carefully, as changing this decision on a later phase of development is complicated . 

That is the topic that I am researching now, and if someone wants to collaborate I will be glad to get in touch.

Best,
Dmitry

**Comment by nightscape** [comment]
Hi Dmitry,

I was refering to Scala Streams and after watching your talk from ScalaDays (nice one!!) I see that ScalaBlitz's focus is a different one. Actually, a parallel Stream should be implemented in Scala itself, as is a parallel list and other collections.
Maybe I write a PR for Scala if I dare to ;)

Thanks for your elaborate response!
  Martin
